name: oklab
description: Oklab color space implementation.
version: 0.0.1
repository: https://github.com/hawkkiller/oklab
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
