name: example
description: oklab_flutter example app.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  oklab_flutter:
    path: ..

dependency_overrides:
  oklab:
    path: ../../oklab

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
